config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  resources :users do
    resources :tournaments, only: [:index, :new]
    resources :opponents, only: [:index]
  end

  resources :tournaments
  resources :matches
  resources :opponents
  resources :style_tags, except: [:show]

  get '/login' => "sessions#new"
  post '/login' => "sessions#create"
  get '/logout' => 'sessions#destroy'
  get '/auth/facebook/callback' => 'sessions#create_facebook_omniauth'
end

app/models/style_tag.rb
class StyleTag < ApplicationRecord
  has_many :opponent_style_tags, dependent: :nullify
  has_many :opponents, through: :opponent_style_tags
end

app/controllers/style_tags_controller.rb
class StyleTagsController < ApplicationController
  before_action :set_style_tag, only:[:edit, :update, :destroy]

  def index
    @style_tags = StyleTag.all
    respond_to do |f|
      f.html {render :index}
      f.json {render json: @style_tags}
    end
  end

  def new
    @style_tag = StyleTag.new
  end

  def create
    StyleTag.create(style_tag_params)
    redirect_to user_path(current_user)
  end

  def edit
  end

  def update
    @style_tag.update(style_tag_params)
    redirect_to style_tags_path
  end

  def destroy
    @style_tag.destroy
    redirect_to style_tags_path
  end

  private

  def set_style_tag
    @style_tag = StyleTag.find(params[:id])
  end

  def style_tag_params
    params.require(:style_tag).permit(:name)
  end
end

app/helpers/style_tags_helper.rb
module StyleTagsHelper
end

app/views/style_tags/_form.html.erb
<%= form_for @style_tag do |f| %>
  <p>
    <%= f.label "Name" %>
    <%= f.text_field :name, required: true %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/style_tags/edit.html.erb
<h1>Edit Style Tag</h1>

<%= render 'form' %>

app/views/style_tags/index.html.erb
<h1 class="inline">Style Tags</h1> <%= link_to "Add Tag", new_style_tag_path %>

<ul>
<% @style_tags.each do |tag| %>
  <li><%= tag.name %> <%= link_to "Edit", edit_style_tag_path(tag), class: "small" %> <%= link_to "Delete", style_tag_path(tag), method: :delete, class: "small" %></li>
<% end %>
</ul>

app/views/style_tags/new.html.erb
<h1>Add A New Style Tag</h1>

<%= render 'form' %>