config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  resources :users do
    resources :tournaments, only: [:index, :new]
    resources :opponents, only: [:index]
  end

  resources :tournaments
  resources :matches
  resources :opponents
  resources :style_tags, except: [:show]

  get '/login' => "sessions#new"
  post '/login' => "sessions#create"
  get '/logout' => 'sessions#destroy'
  get '/auth/facebook/callback' => 'sessions#create_facebook_omniauth'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tournaments
  has_many :matches, through: :tournaments
  has_many :opponents, through: :matches

  has_secure_password

  validates :email, uniqueness: true

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def overall_record
    "#{self.match_wins} - #{self.match_losses}"
  end

  def add_win
    self.match_wins += 1
    self.save
  end

  def add_loss
    self.match_losses += 1
    self.save
  end

  def remove_win
    self.match_wins -= 1
    self.save
  end

  def remove_loss
    self.match_losses -= 1
    self.save
  end

  def convert_facebook_name
    first_name = self.name.split.first
    last_name = self.name.split.last
    self.update(first_name: first_name, last_name: last_name)
  end

  def record_vs(opponent)
    opponent_matches = self.matches.select {|match| match.opponent = opponent}
    wins = opponent_matches.select {|match| match.won = true}
    losses = opponent_matches.select {|match| match.won = false}
    "#{wins.count} - #{losses.count}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, :set_user, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:alert] = "*Invalid Email or Password. Please make sure email is original and passwords match"
      render new_user_path
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      @user.update(user_params)
      redirect_to user_path(@user)
    else
      flash[:alert] = "*Invalid Email or Password. Please make sure email is original and passwords match"
      redirect_to edit_user_path(@user)
    end
  end

  def destroy
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :name, :image, :uid)
  end

  def set_user
    @user = current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <p>
    <%= f.label "First Name:" %>
    <%= f.text_field :first_name %>
  </p>
  <p>
    <%= f.label "Last Name:" %>
    <%= f.text_field :last_name %>
  </p>
  <p>
    <% if !@user.uid %>
      <%= f.label :email %>
      <%= f.text_field :email %>
    <% else %>
      Email: <%= @user.email %> - Set Through Facebook
    <% end %>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.password_field :password, required: true %>
  </p>
  <p>
    <%= f.label "Password Confirmation" %>
    <%= f.password_field :password_confirmation, required: true %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end  %>

app/views/users/edit.html.erb
<h1>Edit Your Profile</h1>

<%= render 'form' %>

<% content_for :footer do %>
  <%= link_to "Back To Profile", user_path(current_user) %>
  <br>
  <br>
<% end %>

app/views/users/new.html.erb
<h1>Create Your Account</h1>

<%= render 'form' %>

<p>or</p>

<p><%= link_to "Back To Homepage", root_path %></p>

app/views/users/show.html.erb
<h1 class="inline">Your Profile</h1> <%= link_to "Edit Profile", edit_user_path(current_user) %>

<p><b>Name:</b> <%= @user.full_name %></p>
<p><b>Email:</b> <%= @user.email %></p>
<p><b>Overall Record:</b> <%= @user.overall_record %></p>
<p><b>Total Points:</b> <%= @user.points %></p>

<p>
  <div id="data-links">
    <%= link_to "Show Tournaments", user_tournaments_path(@user), id: "tournaments-data", value: @user.id %> <%= link_to "Show Style Tags", style_tags_path, id: "style-tags-data" %> <%= link_to "Show Previous Opponents", user_opponents_path(@user), id:"opponents-data" %>
  </div>
</p>

<div id="show-data">
</div>