config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  resources :users do
    resources :tournaments, only: [:index, :new]
    resources :opponents, only: [:index]
  end

  resources :tournaments
  resources :matches
  resources :opponents
  resources :style_tags, except: [:show]

  get '/login' => "sessions#new"
  post '/login' => "sessions#create"
  get '/logout' => 'sessions#destroy'
  get '/auth/facebook/callback' => 'sessions#create_facebook_omniauth'
end

app/models/tournament.rb
class Tournament < ApplicationRecord
  belongs_to :user
  has_many :matches

  def points_gained?
    self.points != 0
  end

  def round_options_numbers
    options = [256, 128, 64, 32, 16, 8, 4, 2]
    starting_round = options.index(self.draw_size)

    options[starting_round..-1]
  end

  def convert_round_options
    @options.map! do |option|
      if option == 8
        "Quarter-Final"
      elsif option == 4
        "Semi-Final"
      elsif option == 2
        "Final"
      else
        option
      end
    end
    @options
  end

  def round_options
    @options = self.round_options_numbers
    self.matches.each do |match|
      if @options.include?(match.round)
        @options -= [match.round]
      end
    end
    convert_round_options
  end

  def draw_size_options
    [256, 128, 64, 32, 16, 8, 4, 2]
  end

  def result
    if in_progress?
      "In Progress"
    elsif self.matches.all? {|match| match.won == true}
      self.update(won: true)
      "Won"
    else
      self.update(won: false)
      "Lost in #{losing_match.round_num_or_name}" if losing_match
    end
  end

  def losing_match
    losing_match ||= self.matches.find {|match| match.won == false}
  end

  def in_progress?
    self.matches.size < self.round_options_numbers.size && !losing_match
  end

  def add_points_to_user
    self.user.points += self.points
    self.user.save
  end

  def remove_points_from_user
    if self.points
      self.user.points -= self.points
      self.user.save
    end
  end

  def update_user_points
    if self.points_gained?
      add_points_to_user
    end
  end

  def destroy_all_matches
    self.matches.each do |match|
      match.remove_from_user_record
      match.destroy
    end
  end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :require_login
  before_action :set_tournament, only: [:show, :edit, :update, :destroy]
  helper_method :draw_size_options

  def new
    @tournament = Tournament.new
  end

  def create
    @tournament = Tournament.new(tournament_params)
    @tournament.user_id = current_user.id
    @tournament.save
    if @tournament.points
      @tournament.update_user_points
    end

    redirect_to tournament_path(@tournament)
  end

  def index
    if params[:user_id]
      @tournaments = tournaments_sorted_by_date
    end

    respond_to do |f|
      f.html {render :index}
      f.json {render json: @tournaments}
    end
  end

  def show
    @match = @tournament.matches.build
    @match.build_opponent
    @tournaments = current_user.tournaments
    respond_to do |f|
      f.html {render :show}
      f.json {render json: @tournament}
    end
  end

  def edit
  end

  def update
    @tournament.remove_points_from_user
    @tournament.update(tournament_params)

    if @tournament.points
      @tournament.update_user_points
    end

    redirect_to tournament_path(@tournament)
  end

  def destroy
    @tournament.remove_points_from_user
    @tournament.destroy_all_matches
    @tournament.destroy
    redirect_to user_path(current_user)
  end

  private

  def tournament_params
    params.require(:tournament).permit(:title, :start_date, :end_date, :location, :draw_size, :points)
  end

  def set_tournament
    @tournament = Tournament.find_by_id(params[:id])
  end

  def tournaments_sorted_by_date
    tournament_array = User.find(params[:user_id]).tournaments
    tournament_array.sort_by {|tournament| tournament.start_date}
  end
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/tournaments/_form.html.erb
<%= form_for @tournament do |f| %>
  <p>
    <%= f.label "Title" %>
    <%= f.text_field :title, required: true %>
  </p>
  <p>
    <%= f.label "Start Date" %>
    <%= f.date_field :start_date, required: true  %>
  </p>
  <p>
    <%= f.label "End Date" %>
    <%= f.date_field :end_date, required: true %>
  </p>
  <p>
    <%= f.label "Location" %>
    <%= f.text_field :location %>
  </p>
  <p>
    <%= f.label "Draw Size" %>
    <%= f.select :draw_size, @tournament.draw_size_options %>
  </p>
  <p>
    <%= f.label "Points Won" %>
    <%= f.number_field :points %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/tournaments/edit.html.erb
<h1>Edit Tournament</h1>

<%= render 'form' %>

app/views/tournaments/index.html.erb
<h1 class="inline">Tournaments</h1> <%= link_to "Add A Tournament", new_user_tournament_path(current_user) %>

<% @tournaments.each_with_index do |tournament, index| %>
  <p><%= index + 1 %>. <%= link_to "#{tournament.title}", tournament_path(tournament) %></p>
<% end %>

<% content_for :footer do %>
  <br>
  <br>
<% end %>

app/views/tournaments/new.html.erb
<h1>Add A Tournament</h1>

<%= render 'form' %>

app/views/tournaments/show.html.erb
<h1 class="inline"><%= @tournament.title %></h1> <%= link_to "Edit", edit_tournament_path(@tournament) %> <%= link_to "Delete", tournament_path(@tournament), method: :delete %>

<p><b>Start Date:</b> <%= @tournament.start_date.strftime("%m/%d/%Y") if @tournament.start_date %></p>
<p><b>End Date:</b> <%= @tournament.end_date.strftime("%m/%d/%Y") if @tournament.end_date %></p>
<p><b>Location:</b> <%= @tournament.location %></p>
<p><b>Draw Size:</b> <%= @tournament.draw_size %></p>
<p><b>Points Won:</b> <%= @tournament.points %></p>
<p><b>Result:</b> <%= @tournament.result %></p>


<p><a href="" id="show-matches-link" style="display:none"></a></p>

<div id="all-match-display" style="">
  <h2>Matches</h2>
  <% @tournament.matches.each_with_index do |match, index| %>
    <% if match.round %>
      <p><%= link_to "#{match.round_num_or_name} vs #{match.opponent.full_name}", match_path(match), class:"match-link" %> - <%= match.result %></p>
    <% end %>
  <% end %>

  <% content_for :footer do %>
    <br>
    <br>
  <% end %>
</div>
<p><%= link_to "Add Match", new_match_path(:tournament_id => @tournament.id), id:"add-match" %></p>

<div id="single-match-display">
</div>
<div id="new-match-form" style="display:none">
  <h2 style="margin-bottom: -5px" class="inline">Add A New Match</h2> <a href="" id="hide-form">Hide Form</a>
  <p><%= render 'matches/opponent_form' %></p>
</div>