config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  resources :users do
    resources :tournaments, only: [:index, :new]
    resources :opponents, only: [:index]
  end

  resources :tournaments
  resources :matches
  resources :opponents
  resources :style_tags, except: [:show]

  get '/login' => "sessions#new"
  post '/login' => "sessions#create"
  get '/logout' => 'sessions#destroy'
  get '/auth/facebook/callback' => 'sessions#create_facebook_omniauth'
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :tournament
  has_one :opponent
  accepts_nested_attributes_for :opponent

  def round_options
    options = [256, 128, 64, 32, 16, 8, 4, 2]
    start_point = options.index(self.round)
    @options = options[start_point..-1]
    convert_round_options
    @options
  end

  def convert_round_options
    @options.map! do |option|
      if option == 8
        "Quarter-Final"
      elsif option == 4
        "Semi-Final"
      elsif option == 2
        "Final"
      else
        option
      end
    end
    @options
  end

  def round_num_or_name
    case self.round
    when 2
      "Final"
    when 4
      "Semi-Final"
    when 8
      "Quarter-Final"
    else
      "Round of #{self.round}"
    end
  end

  def select_default_round
    case self.round
    when 2
      "Final"
    when 4
      "Semi-Final"
    when 8
      "Quarter-Final"
    else
      self.round
    end
  end

  def result
    if self.won
      "Won"
    else
      "Lost"
    end
  end

  def add_to_user_record
    if self.won
      self.tournament.user.add_win
    else
      self.tournament.user.add_loss
    end
  end

  def remove_from_user_record
    if self.won
      self.tournament.user.remove_win
    else
      self.tournament.user.remove_loss
    end
  end

  def update_user_record
    if self.won
      self.tournament.user.add_win
      self.tournament.user.remove_loss
    else
      self.tournament.user.add_loss
      self.tournament.user.remove_win
    end
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :require_login
  before_action :set_match, only: [:show, :edit, :update, :destroy]
  before_action :convert_params_round_to_number, only: [:create, :update]
  before_action :set_tournaments, only: [:new, :edit]

  def new
    @match = Match.new
    @match.build_opponent
    @tournament = Tournament.find_by_id(params[:tournament_id])
  end

  def create
    @match = Match.create(match_params)
    @match.add_to_user_record
    # redirect_to match_path(@match)
    render 'matches/link', layout: false
  end

  def show
    respond_to do |f|
      f.html {render :show}
      f.json {render json: @match}
    end
  end

  def edit
    @tournament = @match.tournament
    @opponent = @match.opponent
  end

  def update
    @match.update(match_params)
    @match.update_user_record
    redirect_to tournament_path(@match.tournament)
  end

  def destroy
    tournament = @match.tournament
    @match.remove_from_user_record
    @match.destroy
    redirect_to tournament_path(tournament)
  end

  private

  def match_params
    params.require(:match).permit(:date, :time, :round, :score, :won, :tournament_id, opponent_id:[], opponent_attributes: [:first_name, :last_name, :age, :handedness])
  end

  def set_match
    @match = Match.find(params[:id])
  end

  def set_tournaments
    @tournaments = current_user.tournaments.all
  end

  def convert_params_round_to_number
    case params[:match][:round]
    when "Quarter-Final"
      params[:match][:round] = 8
    when "Semi-Final"
      params[:match][:round] = 4
    when "Final"
      params[:match][:round] = 2
    end
  end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<%= form_for @match do |f| %>
  <p>
    <%= f.label "Date" %>
    <%= f.date_field :date, required: true %>
  </p>
  <p>
    <%= f.label "Time" %>
    <%= f.time_field :time %>
  </p>
  <p>
    <%= f.label "Tournament" %>
    <%= f.collection_select(:tournament_id, @tournaments, :id, :title, {selected: @tournament.id}) %>
  </p>
  <p>
    <%= f.label "Round" %>
    <% if @match.round %>
      <%= f.select :round, @match.round_options, selected: @match.select_default_round  %>
    <% else %>
      <%= f.select :round, @tournament.round_options %>
    <% end %>
  </p>
  <p>
    <%= f.label "Score" %>
    <%= f.text_field :score, required: true %>
  </p>
  <p>
    <%= f.label "Check Box If You Won" %>
    <%= f.check_box :won %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/matches/_opponent_form.html.erb
<%= form_for(@match, url:{controller:'matches', action:'create'}, method:'post') do |f| %>
  <p>
    <%= f.label "Date" %>
    <%= f.date_field :date, required: true %>
  </p>
  <p>
    <%= f.label "Time" %>
    <%= f.time_field :time %>
  </p>
  <p>
    <%= f.label "Tournament" %>
    <%= f.collection_select(:tournament_id, @tournaments, :id, :title, {selected: @tournament.id}) %>
  </p>
  <p>
    <%= f.label "Round" %>
    <%= f.select :round, @tournament.round_options %>
  </p>
  <p>
    <%= f.label "Score" %>
    <%= f.text_field :score, required: true %>
  </p>
  <p>
    <%= f.label "Check Box If You Won" %>
    <%= f.check_box :won %>
  </p>
  <h3>Opponent:</h3>
    <%= f.fields_for :opponent do |opponent_builder| %>
      <p>
        <%= opponent_builder.label "First Name" %>
        <%= opponent_builder.text_field :first_name, required: true %>
      </p>
      <p>
        <%= opponent_builder.label "Last Name" %>
        <%= opponent_builder.text_field :last_name, required: true %>
      <p>
      <p>
        <%= opponent_builder.label "Age" %>
        <%= opponent_builder.number_field :age %>
      </p>
      <p>
        <%= opponent_builder.label "Plays" %>
        <%= opponent_builder.text_field :handedness %>
        <%= opponent_builder.label "Handed" %>
      </p>
    <% end %>
  <p>
    <% if @match.round %>
      <%= f.submit %>
    <% else %>
      <%= f.submit "Add Match", data: { disable_with: false } %>
    <% end %>
  </p>
<% end %>

app/views/matches/edit.html.erb
<h1>Edit Match</h1>

<h3>vs: <%= link_to "#{@opponent.full_name}", edit_opponent_path(@opponent) %></h3>

<%= render 'form' %>

<% content_for :footer do %>
  <%= link_to "Back To Match", match_path(@match) %>
  <br>
  <br>
<% end %>

app/views/matches/link.html.erb
<p><%= link_to "#{@match.round_num_or_name} vs #{@match.opponent.full_name}", match_path(@match), class:"match-link" %> - <%= @match.result %></p>

app/views/matches/new.html.erb
<h1>Add A Match</h1>

<%= render 'opponent_form' %>

<% content_for :footer do %>
  <%= link_to "Back To Tournament", tournament_path(@tournament) %>
  <br>
  <br>
<% end %>

app/views/matches/show.html.erb
<h1 class="inline"><%= @match.round_num_or_name %></h1> <%= link_to "Edit Match", edit_match_path(@match) %> <%= link_to "Delete Match", match_path(@match), method: :delete %>
<p><%= @match.tournament.title %></p>

<h3>vs: <%= link_to "#{@match.opponent.full_name}", opponent_path(@match.opponent) %></h3>
<p><b>Date:</b> <%= @match.date.strftime("%m/%d/%Y") if @match.date %></p>
<p><b>Time:</b> <%= @match.time.strftime("%l:%M%p") if @match.time %></p>
<p><b>Score:</b> <%= @match.score %></p>
<% if @match.won %>
  <p><b>Result:</b> Won</p>
<% else %>
  <p><b>Result:</b> Lost</p>
<% end %>

<% content_for :footer do %>
  <%= link_to "Back To Tournament", tournament_path(@match.tournament) %>
  <br>
  <br>
<% end %>